type: button
widget_id: su_configdatainstall-widget
api_url: /module/softwareupdate/get_binary_widget/configdatainstall
i18n_title: softwareupdate.configdatainstall_widget
icon: fa-shield
listing_link: /show/listing/softwareupdate/softwareupdate
buttons:
  - label: "0"
    i18n_label: no
    class: btn-danger 
  - label: "1"
    i18n_label: yes
    class: btn-success
